1.	name: ci
2.	
3.	on:
4.	  push:
5.	    branches:
6.	      - main
7.	
8.	jobs:
9.	  build:
10.	    runs-on: ubuntu-latest
11.	    steps:
12.	      - name: Login to Docker Hub
13.	        uses: docker/login-action@v3
14.	        with:
15.	          username: ${{ vars.DOCKER_USERNAME }}
16.	          password: ${{ secrets.DOCKERHUB_TOKEN }}
17.	
18.	      - name: Set up Docker Buildx
19.	        uses: docker/setup-buildx-action@v3
20.	
21.	      - name: Build and test
22.	        uses: docker/build-push-action@v6
23.	        with:
24.	          target: test
25.	          load: true
26.	
27.	      - name: Build and push
28.	        uses: docker/build-push-action@v6
29.	        with:
30.	          platforms: linux/amd64,linux/arm64
31.	          push: true
32.	          target: final
          tags: ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest
